---
title: "Software tools for geospatial analysis"
output:
    html_document:
        number_sections: false
        theme: flatly
---

This site contains live versions of the examples discussed in the paper 
[A review of software tools, data and services for geospatial analysis of stroke services](https:/frontiersin.org/)

The examples can be accessed via the navigation bar above. There are several
implementations of two examples: 

1. A choropleth, or thematic map, displaying
per-postcode estimates of stroke cases.

1. An example of estimating catchment zones for rehabilitation centers,
and the resulting load on centers, based on distances through the
road network.

The examples are illustrated using both _R_ and _Python_.

A more advanced version of the second example, that uses web services
requiring API keys, is also provided. Interested readers must create
the relevant accounts and install the necessary keys in order to
explore this example fully.

## Getting started

For convenience, the supplementary material from the paper, providing
some instructions for getting started, is available [here](supplementary.html)

The [Software Carpentries](https://software-carpentry.org/) are an excellent source of training material
for readers getting started with _R_ and _Python_.

## Source code

Recreating the examples requires a local installation of _R_ and/or _Python_
and copies of the source code.

R and python source code for these examples is available from the [github site](https://github.com/richardbeare/GeospatialStroke/) or can be 
download as a 
[zip file](https://github.com/richardbeare/GeospatialStroke/archive/master.zip)

The _Choropleth_ example for _R_ is in `Choropleth/mmc_surrounds.Rmd` and `Choropleth/mmc_surrounds.R`.

The _Catchment Zones_ example of _R_ is in `RehabCatchment/README.Rmd`.

The _Choropleth_ example for _Python_ is in `python/notebooks/example1.pynb`.

The _Catchment Zones_ example of _Python_ is in `python/notebooks/example1.pynb`.


## Problems

Please use the github [issue tracker](https://github.com/richardbeare/GeospatialStroke/issues) to ask questions or point out problems.